kind: Secret
apiVersion: v1
metadata:
  name: che-env-vars
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-secret: 'true'
  annotations:
    controller.devfile.io/mount-as: env
data:
  WEAVIATE_API_KEY: Y2hhbmdlX21l
  WEAVIATE_HOST: d2VhdmlhdGUud2VhdmlhdGU=
  OLLAMA_HOST: aHR0cDovL29sbGFtYS5vbGxhbWE6MTE0MzQ=
type: Opaque

