---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weaviate-config
  labels:
    app.kubernetes.io/name: weaviate
data:
  conf.yaml: |-
    ---
    authentication:
      anonymous_access:
        enabled: false
      apikey:
        allowed_keys:
        - abc123xyz-readOnly-plainText-API-Key
        - abc123xyz-admin-plainText-API-Key
        enabled: true
        users:
        - api-key-user-readOnly
        - api-key-user-admin
      oidc:
        enabled: false
    authorization:
      admin_list:
        enabled: false
      rbac:
        enabled: false
    query_defaults:
      limit: 100
    debug: false
