---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weaviate-config
  labels:
    app.kubernetes.io/name: weaviate
data:
  conf.yaml: |-
    ---
    authentication:
      anonymous_access:
        enabled: true
      oidc:
        enabled: false
    authorization:
      admin_list:
        enabled: false
      rbac:
        enabled: false
    query_defaults:
      limit: 100
    debug: false
