---
# Source: weaviate/templates/weaviateSecretClusterAPI.yaml
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-cluster-api-basic-auth
type: kubernetes.io/basic-auth
data:  
  username: "V3RBS0NRZDhtMmxGeEpMczR6YzNYWW4yMHlwMzhNeDk="
  password: "aFFvcXd2MkdIWWFWd01tYVR0QzdmaEZTQTc4b1hhYW8="
